/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PlayerRegistry {
      
    export type PlayerProfileStruct = {registered: boolean, registeredAt: BigNumberish, gamesPlayed: BigNumberish, roundsSurvived: BigNumberish, enemiesKilled: BigNumberish, sbtCount: BigNumberish, reputationScore: BigNumberish, externalWallet: AddressLike, banned: boolean, banCount: BigNumberish}

    export type PlayerProfileStructOutput = [registered: boolean, registeredAt: bigint, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint, sbtCount: bigint, reputationScore: bigint, externalWallet: string, banned: boolean, banCount: bigint] & {registered: boolean, registeredAt: bigint, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint, sbtCount: bigint, reputationScore: bigint, externalWallet: string, banned: boolean, banCount: bigint }
  
    }

  export interface PlayerRegistryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "RECORDER_ROLE" | "SBT_CONTRACT_ROLE" | "banPlayer" | "getProfile" | "getRoleAdmin" | "grantRole" | "hasRole" | "incrementSbtCount" | "isActivePlayer" | "linkExternalWallet" | "profiles" | "recordStats" | "registerPlayer" | "renounceRole" | "revokeRole" | "setSbtContract" | "supportsInterface" | "totalPlayers" | "unbanPlayer" | "updateReputation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExternalWalletLinked" | "PlayerBanned" | "PlayerRegistered" | "PlayerUnbanned" | "ReputationUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SbtCountIncremented" | "StatsRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'RECORDER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SBT_CONTRACT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'banPlayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'incrementSbtCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isActivePlayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'linkExternalWallet', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'profiles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'recordStats', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerPlayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setSbtContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalPlayers', values?: undefined): string;
encodeFunctionData(functionFragment: 'unbanPlayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateReputation', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RECORDER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SBT_CONTRACT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'banPlayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementSbtCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivePlayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'linkExternalWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'profiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPlayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSbtContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPlayers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbanPlayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateReputation', data: BytesLike): Result;
  }

  
    export namespace ExternalWalletLinkedEvent {
      export type InputTuple = [custodialWallet: AddressLike, externalWallet: AddressLike];
      export type OutputTuple = [custodialWallet: string, externalWallet: string];
      export interface OutputObject {custodialWallet: string, externalWallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlayerBannedEvent {
      export type InputTuple = [wallet: AddressLike];
      export type OutputTuple = [wallet: string];
      export interface OutputObject {wallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlayerRegisteredEvent {
      export type InputTuple = [wallet: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [wallet: string, timestamp: bigint];
      export interface OutputObject {wallet: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlayerUnbannedEvent {
      export type InputTuple = [wallet: AddressLike];
      export type OutputTuple = [wallet: string];
      export interface OutputObject {wallet: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReputationUpdatedEvent {
      export type InputTuple = [wallet: AddressLike, oldScore: BigNumberish, newScore: BigNumberish];
      export type OutputTuple = [wallet: string, oldScore: bigint, newScore: bigint];
      export interface OutputObject {wallet: string, oldScore: bigint, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SbtCountIncrementedEvent {
      export type InputTuple = [wallet: AddressLike, newCount: BigNumberish];
      export type OutputTuple = [wallet: string, newCount: bigint];
      export interface OutputObject {wallet: string, newCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatsRecordedEvent {
      export type InputTuple = [wallet: AddressLike, gamesPlayed: BigNumberish, roundsSurvived: BigNumberish, enemiesKilled: BigNumberish];
      export type OutputTuple = [wallet: string, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint];
      export interface OutputObject {wallet: string, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PlayerRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): PlayerRegistry;
    waitForDeployment(): Promise<this>;

    interface: PlayerRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    RECORDER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SBT_CONTRACT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    banPlayer: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getProfile: TypedContractMethod<
      [wallet: AddressLike, ],
      [PlayerRegistry.PlayerProfileStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    incrementSbtCount: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isActivePlayer: TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    linkExternalWallet: TypedContractMethod<
      [custodialWallet: AddressLike, externalWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    profiles: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean, bigint] & {registered: boolean, registeredAt: bigint, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint, sbtCount: bigint, reputationScore: bigint, externalWallet: string, banned: boolean, banCount: bigint }],
      'view'
    >
    

    
    recordStats: TypedContractMethod<
      [wallet: AddressLike, games: BigNumberish, rounds: BigNumberish, enemies: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerPlayer: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setSbtContract: TypedContractMethod<
      [sbtContract: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalPlayers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unbanPlayer: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateReputation: TypedContractMethod<
      [wallet: AddressLike, newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'RECORDER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SBT_CONTRACT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'banPlayer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProfile'): TypedContractMethod<
      [wallet: AddressLike, ],
      [PlayerRegistry.PlayerProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'incrementSbtCount'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isActivePlayer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'linkExternalWallet'): TypedContractMethod<
      [custodialWallet: AddressLike, externalWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'profiles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean, bigint] & {registered: boolean, registeredAt: bigint, gamesPlayed: bigint, roundsSurvived: bigint, enemiesKilled: bigint, sbtCount: bigint, reputationScore: bigint, externalWallet: string, banned: boolean, banCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'recordStats'): TypedContractMethod<
      [wallet: AddressLike, games: BigNumberish, rounds: BigNumberish, enemies: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerPlayer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSbtContract'): TypedContractMethod<
      [sbtContract: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalPlayers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unbanPlayer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateReputation'): TypedContractMethod<
      [wallet: AddressLike, newScore: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ExternalWalletLinked'): TypedContractEvent<ExternalWalletLinkedEvent.InputTuple, ExternalWalletLinkedEvent.OutputTuple, ExternalWalletLinkedEvent.OutputObject>;
getEvent(key: 'PlayerBanned'): TypedContractEvent<PlayerBannedEvent.InputTuple, PlayerBannedEvent.OutputTuple, PlayerBannedEvent.OutputObject>;
getEvent(key: 'PlayerRegistered'): TypedContractEvent<PlayerRegisteredEvent.InputTuple, PlayerRegisteredEvent.OutputTuple, PlayerRegisteredEvent.OutputObject>;
getEvent(key: 'PlayerUnbanned'): TypedContractEvent<PlayerUnbannedEvent.InputTuple, PlayerUnbannedEvent.OutputTuple, PlayerUnbannedEvent.OutputObject>;
getEvent(key: 'ReputationUpdated'): TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SbtCountIncremented'): TypedContractEvent<SbtCountIncrementedEvent.InputTuple, SbtCountIncrementedEvent.OutputTuple, SbtCountIncrementedEvent.OutputObject>;
getEvent(key: 'StatsRecorded'): TypedContractEvent<StatsRecordedEvent.InputTuple, StatsRecordedEvent.OutputTuple, StatsRecordedEvent.OutputObject>;

    filters: {
      
      'ExternalWalletLinked(address,address)': TypedContractEvent<ExternalWalletLinkedEvent.InputTuple, ExternalWalletLinkedEvent.OutputTuple, ExternalWalletLinkedEvent.OutputObject>;
      ExternalWalletLinked: TypedContractEvent<ExternalWalletLinkedEvent.InputTuple, ExternalWalletLinkedEvent.OutputTuple, ExternalWalletLinkedEvent.OutputObject>;
    

      'PlayerBanned(address)': TypedContractEvent<PlayerBannedEvent.InputTuple, PlayerBannedEvent.OutputTuple, PlayerBannedEvent.OutputObject>;
      PlayerBanned: TypedContractEvent<PlayerBannedEvent.InputTuple, PlayerBannedEvent.OutputTuple, PlayerBannedEvent.OutputObject>;
    

      'PlayerRegistered(address,uint256)': TypedContractEvent<PlayerRegisteredEvent.InputTuple, PlayerRegisteredEvent.OutputTuple, PlayerRegisteredEvent.OutputObject>;
      PlayerRegistered: TypedContractEvent<PlayerRegisteredEvent.InputTuple, PlayerRegisteredEvent.OutputTuple, PlayerRegisteredEvent.OutputObject>;
    

      'PlayerUnbanned(address)': TypedContractEvent<PlayerUnbannedEvent.InputTuple, PlayerUnbannedEvent.OutputTuple, PlayerUnbannedEvent.OutputObject>;
      PlayerUnbanned: TypedContractEvent<PlayerUnbannedEvent.InputTuple, PlayerUnbannedEvent.OutputTuple, PlayerUnbannedEvent.OutputObject>;
    

      'ReputationUpdated(address,uint256,uint256)': TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
      ReputationUpdated: TypedContractEvent<ReputationUpdatedEvent.InputTuple, ReputationUpdatedEvent.OutputTuple, ReputationUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SbtCountIncremented(address,uint256)': TypedContractEvent<SbtCountIncrementedEvent.InputTuple, SbtCountIncrementedEvent.OutputTuple, SbtCountIncrementedEvent.OutputObject>;
      SbtCountIncremented: TypedContractEvent<SbtCountIncrementedEvent.InputTuple, SbtCountIncrementedEvent.OutputTuple, SbtCountIncrementedEvent.OutputObject>;
    

      'StatsRecorded(address,uint256,uint256,uint256)': TypedContractEvent<StatsRecordedEvent.InputTuple, StatsRecordedEvent.OutputTuple, StatsRecordedEvent.OutputObject>;
      StatsRecorded: TypedContractEvent<StatsRecordedEvent.InputTuple, StatsRecordedEvent.OutputTuple, StatsRecordedEvent.OutputObject>;
    
    };
  }