/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TreasuryInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "DEFAULT_ADMIN_ROLE" | "DISTRIBUTOR_ROLE" | "MARKETPLACE_ROLE" | "MAX_FEE_BPS" | "batchDistributeReward" | "computeFee" | "distributeReward" | "feeRateBps" | "getRoleAdmin" | "godsReserves" | "godsToken" | "grantRole" | "hasRole" | "receiveFee" | "renounceRole" | "reserves" | "revokeRole" | "setFeeRate" | "soulReserves" | "soulToken" | "supportsInterface" | "withdrawReserves"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchRewardDistributed" | "FeeRateUpdated" | "FeeReceived" | "ReservesWithdrawn" | "RewardDistributed" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DISTRIBUTOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MARKETPLACE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'batchDistributeReward', values: [AddressLike, AddressLike[], BigNumberish[], string]): string;
encodeFunctionData(functionFragment: 'computeFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributeReward', values: [AddressLike, AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'feeRateBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'godsReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'godsToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'receiveFee', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reserves', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'soulReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'soulToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawReserves', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DISTRIBUTOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MARKETPLACE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchDistributeReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRateBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'godsReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'godsToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'soulReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'soulToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawReserves', data: BytesLike): Result;
  }

  
    export namespace BatchRewardDistributedEvent {
      export type InputTuple = [token: AddressLike, totalAmount: BigNumberish, recipientCount: BigNumberish];
      export type OutputTuple = [token: string, totalAmount: bigint, recipientCount: bigint];
      export interface OutputObject {token: string, totalAmount: bigint, recipientCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeRateUpdatedEvent {
      export type InputTuple = [oldRateBps: BigNumberish, newRateBps: BigNumberish];
      export type OutputTuple = [oldRateBps: bigint, newRateBps: bigint];
      export interface OutputObject {oldRateBps: bigint, newRateBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeReceivedEvent {
      export type InputTuple = [token: AddressLike, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, from: string, amount: bigint];
      export interface OutputObject {token: string, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReservesWithdrawnEvent {
      export type InputTuple = [token: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, to: string, amount: bigint];
      export interface OutputObject {token: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardDistributedEvent {
      export type InputTuple = [token: AddressLike, recipient: AddressLike, amount: BigNumberish, reason: string];
      export type OutputTuple = [token: string, recipient: string, amount: bigint, reason: string];
      export interface OutputObject {token: string, recipient: string, amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Treasury extends BaseContract {
    
    connect(runner?: ContractRunner | null): Treasury;
    waitForDeployment(): Promise<this>;

    interface: TreasuryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DISTRIBUTOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MARKETPLACE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    batchDistributeReward: TypedContractMethod<
      [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[], reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    computeFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    distributeReward: TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    feeRateBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    godsReserves: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    godsToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    receiveFee: TypedContractMethod<
      [token: AddressLike, from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reserves: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRate: TypedContractMethod<
      [newRateBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    soulReserves: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    soulToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    withdrawReserves: TypedContractMethod<
      [token: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DISTRIBUTOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MARKETPLACE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'batchDistributeReward'): TypedContractMethod<
      [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[], reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'computeFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distributeReward'): TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRateBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'godsReserves'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'godsToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'receiveFee'): TypedContractMethod<
      [token: AddressLike, from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reserves'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRate'): TypedContractMethod<
      [newRateBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'soulReserves'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'soulToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawReserves'): TypedContractMethod<
      [token: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BatchRewardDistributed'): TypedContractEvent<BatchRewardDistributedEvent.InputTuple, BatchRewardDistributedEvent.OutputTuple, BatchRewardDistributedEvent.OutputObject>;
getEvent(key: 'FeeRateUpdated'): TypedContractEvent<FeeRateUpdatedEvent.InputTuple, FeeRateUpdatedEvent.OutputTuple, FeeRateUpdatedEvent.OutputObject>;
getEvent(key: 'FeeReceived'): TypedContractEvent<FeeReceivedEvent.InputTuple, FeeReceivedEvent.OutputTuple, FeeReceivedEvent.OutputObject>;
getEvent(key: 'ReservesWithdrawn'): TypedContractEvent<ReservesWithdrawnEvent.InputTuple, ReservesWithdrawnEvent.OutputTuple, ReservesWithdrawnEvent.OutputObject>;
getEvent(key: 'RewardDistributed'): TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'BatchRewardDistributed(address,uint256,uint256)': TypedContractEvent<BatchRewardDistributedEvent.InputTuple, BatchRewardDistributedEvent.OutputTuple, BatchRewardDistributedEvent.OutputObject>;
      BatchRewardDistributed: TypedContractEvent<BatchRewardDistributedEvent.InputTuple, BatchRewardDistributedEvent.OutputTuple, BatchRewardDistributedEvent.OutputObject>;
    

      'FeeRateUpdated(uint256,uint256)': TypedContractEvent<FeeRateUpdatedEvent.InputTuple, FeeRateUpdatedEvent.OutputTuple, FeeRateUpdatedEvent.OutputObject>;
      FeeRateUpdated: TypedContractEvent<FeeRateUpdatedEvent.InputTuple, FeeRateUpdatedEvent.OutputTuple, FeeRateUpdatedEvent.OutputObject>;
    

      'FeeReceived(address,address,uint256)': TypedContractEvent<FeeReceivedEvent.InputTuple, FeeReceivedEvent.OutputTuple, FeeReceivedEvent.OutputObject>;
      FeeReceived: TypedContractEvent<FeeReceivedEvent.InputTuple, FeeReceivedEvent.OutputTuple, FeeReceivedEvent.OutputObject>;
    

      'ReservesWithdrawn(address,address,uint256)': TypedContractEvent<ReservesWithdrawnEvent.InputTuple, ReservesWithdrawnEvent.OutputTuple, ReservesWithdrawnEvent.OutputObject>;
      ReservesWithdrawn: TypedContractEvent<ReservesWithdrawnEvent.InputTuple, ReservesWithdrawnEvent.OutputTuple, ReservesWithdrawnEvent.OutputObject>;
    

      'RewardDistributed(address,address,uint256,string)': TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
      RewardDistributed: TypedContractEvent<RewardDistributedEvent.InputTuple, RewardDistributedEvent.OutputTuple, RewardDistributedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }