/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPlayerRegistry } from './IPlayerRegistry.js';
export type { ITreasury } from './ITreasury.js';
export type { IUpgradeNFT } from './IUpgradeNFT.js';
export type { Marketplace } from './Marketplace.js';