/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ITreasuryInterface extends Interface {
    getFunction(nameOrSignature: "computeFee" | "feeRateBps" | "receiveFee"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'computeFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeRateBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'receiveFee', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'computeFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRateBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveFee', data: BytesLike): Result;
  }

  

  export interface ITreasury extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITreasury;
    waitForDeployment(): Promise<this>;

    interface: ITreasuryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    computeFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    feeRateBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    receiveFee: TypedContractMethod<
      [token: AddressLike, from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'computeFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRateBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'receiveFee'): TypedContractMethod<
      [token: AddressLike, from: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }