/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IUpgradeNFTInterface extends Interface {
    getFunction(nameOrSignature: "isRentalActive" | "mint" | "mintAndRent" | "ownerOf" | "setUser" | "userOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'isRentalActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintAndRent', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUser', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userOf', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'isRentalActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintAndRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userOf', data: BytesLike): Result;
  }

  

  export interface IUpgradeNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUpgradeNFT;
    waitForDeployment(): Promise<this>;

    interface: IUpgradeNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isRentalActive: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    mintAndRent: TypedContractMethod<
      [owner: AddressLike, renter: AddressLike, typeId: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    setUser: TypedContractMethod<
      [tokenId: BigNumberish, user: AddressLike, expires: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    userOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isRentalActive'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, typeId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintAndRent'): TypedContractMethod<
      [owner: AddressLike, renter: AddressLike, typeId: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setUser'): TypedContractMethod<
      [tokenId: BigNumberish, user: AddressLike, expires: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }