/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPlayerRegistry, IPlayerRegistryInterface } from "../../Marketplace.sol/IPlayerRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      }
    ],
    "name": "isActivePlayer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPlayerRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IPlayerRegistryInterface {
      return new Interface(_abi) as IPlayerRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPlayerRegistry {
      return new Contract(address, _abi, runner) as unknown as IPlayerRegistry;
    }
  }
  